FROM tensorflow/tensorflow:latest-gpu-jupyter

RUN apt-get update
RUN pip install --upgrade pip

RUN apt-get install -y \
    graphviz \
    libgraphviz-dev

RUN pip install pygraphviz

RUN pip install torch torchvision torchaudio

RUN pip install open_spiel

RUN apt-get update && apt-get -y install cmake



